# Active Questions

**Motive**: Create a framework for cleaning and combining this data (rules i.e. do this if X else Y) that 
we can send along to Voya  for validation and generally anwser questions/deliver insights

**Questions**:
- Is it worth combining all of our files together and adding a column for the year?
- Is cik the same across all the years?
- What to do when a year of filing is missing? (Perhaps mock it w/ blank data)
- In terms of LDA/ML, how can we structure this data to quickly/easily retrieve?

# Initial Data Loading

In [1]:
import pandas as pd
import numpy as np

data_by_year = {}
relevant_cols = ["cik", "ticker", "filing_date", "item1a_risk", "item7_mda"]

key = "20"
for i in range(9,21):
    filestub = "0" + str(i) if i <10 else str(i)
    filestub = key + filestub
    data_by_year[filestub] = pd.read_csv(filestub + ".csv", usecols=relevant_cols)
    data_by_year[filestub] = data_by_year[filestub].dropna(subset=['cik', 'item1a_risk', 'item7_mda']).drop_duplicates()

In [3]:
num_rows = np.array([len(year_df) for year_df in data_by_year.values()])
display(num_rows)
display(num_rows.sum())

array([ 964, 3733, 3838, 3918, 3999, 4134, 4278, 4161, 4162, 4190, 4166,
       1979])

43522

# Looking at 10-K field, 2020

In [20]:
""" 2020 has a form_type of 10-K/A, others don't """
# for key, value in data_by_year.items():
#     display(key + ": " + str(value["form_type"].unique()))

""" 2020 has 1876 10-k and 103 10-k/A (ammendments to 10k) -> can we just process this to append the text? """
df_2020 = data_by_year["2020"]
display(len(df_2020))
display((df_2020["form_type"] == "10-K").sum())
display((df_2020["form_type"] == "10-K/A").sum())

1979

1876

103

In [22]:
df_2020.head()

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
0,1630805,BW,10-K,2020-03-30 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk FactorsYou should carefully con...,>Item 7. Management's Discussion and Analysis ...
1,1429260,FBIO,10-K,2020-03-16 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk factors Investing in our Common...,>Item 7. Management s Discussion and Analysis ...
2,1655210,BYND,10-K,2020-03-19 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORS.Investing in our common...,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...
3,949858,OGXI,10-K,2020-03-13 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORS Investing in our common...,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...
4,104889,GHC,10-K,2020-02-26 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors.The Company faces a num...,>Item 7. Management s Discussion and Analysis ...

# Group by CIK

In [23]:
""" Group by cik, print if more than 2 rows"""

# Drop any rows where cik, ticker, fiscal_period_end, item1a_risk, or item7_mda are null
df_2020 = df_2020.dropna(subset=['cik', 'item1a_risk', 'item7_mda'])

def process(group):
    
df_2020 = df_2020.groupby('customer_id').apply(lambda x: process(x))

df_2020 = df_2020.dropna(subset=['cik', 'item1a_risk', 'item7_mda'])

groups_cik = df_2020.groupby("cik")
for key, group in groups_cik:
    if len(group) > 1:
        display(group)

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
341,9346,PTVCB,10-K,2020-03-06 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. RISK FACTORS The following is a desc...,>Item 7. MANAGEMENT'S DISCUSSION AND ANALYSIS ...
854,9346,BWINB,10-K,2020-03-06 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. RISK FACTORS The following is a desc...,>Item 7. MANAGEMENT'S DISCUSSION AND ANALYSIS ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
1838,17843,CRS,10-K,2020-09-04 00:00:00.0,2020-06-30 00:00:00.0,>Item 1A. Risk Factors There are inherent risk...,>Item 7. Management s Discussion and Analysis ...
1850,17843,CRS,10-K,2020-09-04 00:00:00.0,2020-06-30 00:00:00.0,>Item 1A. Risk Factors There are inherent risk...,>Item 7. Management s Discussion and Analysis ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
248,19612,CHFC,10-K,2020-03-02 00:00:00.0,2019-12-31 00:00:00.0,">Item 1A. Risk Factors.There are risks, many b...",>Item 7. Management's Discussion and Analysis ...
1066,19612,TCF,10-K,2020-03-02 00:00:00.0,2019-12-31 00:00:00.0,">Item 1A. Risk Factors.There are risks, many b...",>Item 7. Management's Discussion and Analysis ...
1179,19612,TCF,10-K,2020-03-02 00:00:00.0,2019-12-31 00:00:00.0,">Item 1A. Risk Factors.There are risks, many b...",>Item 7. Management's Discussion and Analysis ...
1494,19612,CHFC,10-K,2020-03-02 00:00:00.0,2019-12-31 00:00:00.0,">Item 1A. Risk Factors.There are risks, many b...",>Item 7. Management's Discussion and Analysis ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
314,23111,CTG,10-K,2020-03-13 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A.Risk Factors The following risk facto...,>Item 7. Management s Discussion and Analysis ...
1153,23111,CTG,10-K,2020-03-13 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A.Risk Factors The following risk facto...,>Item 7. Management s Discussion and Analysis ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
670,31235,KODK,10-K,2020-03-17 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORS Kodak operates in rapid...,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...
687,31235,KODK,10-K,2020-03-17 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORS Kodak operates in rapid...,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
120,77159,PVAC,10-K,2020-02-28 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A Risk Factors Our business and operati...,>Item 7Management s Discussion and Analysis of...
747,77159,PVA,10-K,2020-02-28 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A Risk Factors Our business and operati...,>Item 7Management s Discussion and Analysis of...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
1643,80424,PG,10-K,2020-08-06 00:00:00.0,2020-06-30 00:00:00.0,>Item 1A. Risk Factors.We discuss our expectat...,>Item 7. Management's Discussion and Analysis ...
1657,80424,PG,10-K/A,2020-08-10 00:00:00.0,2020-06-30 00:00:00.0,>Item 1A. Risk Factors.We discuss our expectat...,>Item 7. Management's Discussion and Analysis ...
1771,80424,PG,10-K/A,2020-08-07 00:00:00.0,2020-06-30 00:00:00.0,>Item 1A. Risk Factors.We discuss our expectat...,>Item 7. Management's Discussion and Analysis ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
507,92230,TFC,10-K,2020-03-03 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORSThe following discussion...,>ITEM 7. MANAGEMENT'S DISCUSSION AND ANALYSIS ...
788,92230,TFC,10-K,2020-03-03 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORSThe following discussion...,>ITEM 7. MANAGEMENT'S DISCUSSION AND ANALYSIS ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
184,95574,SCG,10-K,2020-02-20 00:00:00.0,2019-12-31 00:00:00.0,">Item 1A. Risk Factors Our business, operation...",>Item 7. Management s Discussion and Analysis ...
1158,95574,SGC,10-K,2020-02-20 00:00:00.0,2019-12-31 00:00:00.0,">Item 1A. Risk Factors Our business, operation...",>Item 7. Management s Discussion and Analysis ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
1722,98338,TSRI,10-K,2020-08-18 00:00:00.0,2020-05-31 00:00:00.0,>Item 1A. Risk Factors Certain statements cont...,>Item 7. Management s Discussion and Analysis ...
1734,98338,TSRI,10-K,2020-08-17 00:00:00.0,2020-05-31 00:00:00.0,>Item 1A. Risk Factors Certain statements cont...,>Item 7. Management s Discussion and Analysis ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
4,104889,GHC,10-K,2020-02-26 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors.The Company faces a num...,>Item 7. Management s Discussion and Analysis ...
482,104889,WPO,10-K,2020-02-26 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors.The Company faces a num...,>Item 7. Management s Discussion and Analysis ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
211,105319,WW,10-K,2020-02-25 00:00:00.0,2019-12-28 00:00:00.0,>Item 1A. Risk Factors You should consider car...,>Item 7.Management s Discussion and Analysis o...
1023,105319,WW,10-K,2020-02-25 00:00:00.0,2019-12-28 00:00:00.0,>Item 1A. Risk Factors You should consider car...,>Item 7.Management s Discussion and Analysis o...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
1629,108516,WOR,10-K,2020-07-31 00:00:00.0,2020-05-31 00:00:00.0,>Item 1A. Risk Factors Future results and th...,>Item 7. Management s Discussion and Analysi...
1937,108516,WOR,10-K,2020-07-30 00:00:00.0,2020-05-31 00:00:00.0,>Item 1A. Risk Factors Future results and th...,>Item 7. Management s Discussion and Analysi...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
479,314808,ESV,10-K,2020-02-21 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors Risks Related to Our Bu...,>Item 7. Management's Discussion and Analysis ...
701,314808,ESV,10-K,2020-02-21 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors Risks Related to Our Bu...,>Item 7. Management's Discussion and Analysis ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
1049,315858,BBX,10-K,2020-03-13 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORS We are subject to var...,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...
1307,315858,BBX,10-K,2020-03-13 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORS We are subject to var...,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
1658,319201,KLAC,10-K,2020-08-10 00:00:00.0,2020-06-30 00:00:00.0,>ITEM 1A.RISK FACTORSA description of factors ...,>ITEM 7.MANAGEMENT S DISCUSSION AND ANALYSIS O...
1777,319201,KLAC,10-K,2020-08-07 00:00:00.0,2020-06-30 00:00:00.0,>ITEM 1A.RISK FACTORSA description of factors ...,>ITEM 7.MANAGEMENT S DISCUSSION AND ANALYSIS O...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
214,320335,GL,10-K,2020-02-27 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors Risks Related to Our Bu...,>Item 7. Management's Discussion and Analysis ...
332,320335,GL,10-K,2020-02-27 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors Risks Related to Our Bu...,>Item 7. Management's Discussion and Analysis ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
936,351817,SBOW,10-K,2020-03-05 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk FactorsRisks Related to the Bus...,>Item 7. Management s Discussion and Analysis ...
1061,351817,SFY,10-K,2020-03-05 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk FactorsRisks Related to the Bus...,>Item 7. Management s Discussion and Analysis ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
247,704532,ONTO,10-K,2020-02-25 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors. Risks Related to Our B...,>Item 7. Management s Discussion and Analysis ...
902,704532,ONTO,10-K,2020-02-25 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors. Risks Related to Our B...,>Item 7. Management s Discussion and Analysis ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
270,715787,IFSIA,10-K,2020-02-26 00:00:00.0,2019-12-29 00:00:00.0,>ITEM 1A. RISK FACTORS You should carefully co...,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...
1086,715787,IFSIA,10-K,2020-02-26 00:00:00.0,2019-12-29 00:00:00.0,>ITEM 1A. RISK FACTORS You should carefully co...,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
1932,722572,FKWL,10-K,2020-09-17 00:00:00.0,2020-06-30 00:00:00.0,>ITEM 1A: RISK FACTORS. The following risk fac...,>ITEM 7. MANAGEMENT'S DISCUSSION AND ANALYSIS ...
1938,722572,FKWL,10-K/A,2020-09-18 00:00:00.0,2020-06-30 00:00:00.0,>ITEM 1A: RISK FACTORS. The following risk fac...,>ITEM 7. MANAGEMENT'S DISCUSSION AND ANALYSIS ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
584,722723,HGR,10-K,2020-03-11 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A.RISK FACTORS. Set forth below are cer...,>ITEM 7.MANAGEMENT S DISCUSSION AND ANALYSIS O...
1298,722723,HNGR,10-K,2020-03-11 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A.RISK FACTORS. Set forth below are cer...,>ITEM 7.MANAGEMENT S DISCUSSION AND ANALYSIS O...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
195,763744,LCII,10-K,2020-02-27 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A - RISK FACTORS12,>ITEM 7 - MANAGEMENT S DISCUSSION AND ANALYSIS...
387,763744,DW,10-K,2020-02-27 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A - RISK FACTORS12,>ITEM 7 - MANAGEMENT S DISCUSSION AND ANALYSIS...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
359,765880,PEAK,10-K,2020-02-13 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A.Risk Factors The section below discus...,>ITEM 7.Management s Discussion and Analysis o...
643,765880,PEAK,10-K,2020-02-13 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A.Risk Factors The section below discus...,>ITEM 7.Management s Discussion and Analysis o...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
1630,789019,MSFT,10-K,2020-07-31 00:00:00.0,2020-06-30 00:00:00.0,>Item 1A Business model competition Companies ...,>Item 7 Operating income increased $7.9 billio...
1939,789019,MSFT,10-K,2020-07-30 00:00:00.0,2020-06-30 00:00:00.0,>Item 1A Business model competition Companies ...,>Item 7 Operating income increased $7.9 billio...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
1363,808461,GNCMA,10-K,2020-02-27 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors.The risks described bel...,>Item 7. Management s Discussion and Analysis ...
1464,808461,GLIBA,10-K,2020-02-27 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors.The risks described bel...,>Item 7. Management s Discussion and Analysis ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
994,811240,BLTI,10-K,2020-03-30 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors Investing in our securi...,>Item 7. Management s Discussion and Analysis ...
1361,811240,BLTI,10-K,2020-03-30 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors Investing in our securi...,>Item 7. Management s Discussion and Analysis ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
1304,821483,PARR,10-K,2020-03-02 00:00:00.0,2019-12-31 00:00:00.0,">Item 1A. Risk Factors ,",>Item 7. Management s Discussion and Analysi...
1466,821483,DPTR,10-K,2020-03-02 00:00:00.0,2019-12-31 00:00:00.0,">Item 1A. Risk Factors ,",>Item 7. Management s Discussion and Analysi...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
84,827187,SCSS,10-K,2020-02-25 00:00:00.0,2019-12-28 00:00:00.0,>ITEM 1A. RISK FACTORS An investment in our co...,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...
1408,827187,SNBR,10-K,2020-02-25 00:00:00.0,2019-12-28 00:00:00.0,>ITEM 1A. RISK FACTORS An investment in our co...,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
311,876343,LCTX,10-K,2020-03-12 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORS Our business is subject...,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...
639,876343,LCTX,10-K,2020-03-12 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORS Our business is subject...,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
106,878526,NTUS,10-K,2020-03-02 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk FactorsRisks Related to Our Bus...,>ITEM 7. Management s Discussion and Analysis ...
400,878526,NTUS,10-K,2020-03-02 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk FactorsRisks Related to Our Bus...,>ITEM 7. Management s Discussion and Analysis ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
700,883902,CNR,10-K,2020-03-03 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors.Risks related to our in...,>Item 7. Management s Discussion and Analysis ...
893,883902,CNR,10-K,2020-03-03 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors.Risks related to our in...,>Item 7. Management s Discussion and Analysis ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
440,883948,UBSH,10-K,2020-02-25 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. - RISK FACTORSAn investment in the C...,>ITEM 7. - MANAGEMENT S DISCUSSION AND ANALYSI...
803,883948,UBSH,10-K,2020-02-25 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. - RISK FACTORSAn investment in the C...,>ITEM 7. - MANAGEMENT S DISCUSSION AND ANALYSI...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
785,920760,LEN.B,10-K,2020-01-27 00:00:00.0,2019-11-30 00:00:00.0,>Item 1A.Risk Factors.The following are what w...,>Item 7.Management s Discussion and Analysis o...
1019,920760,LEN.B,10-K,2020-01-27 00:00:00.0,2019-11-30 00:00:00.0,>Item 1A.Risk Factors.The following are what w...,>Item 7.Management s Discussion and Analysis o...
1050,920760,LEN,10-K,2020-01-27 00:00:00.0,2019-11-30 00:00:00.0,>Item 1A.Risk Factors.The following are what w...,>Item 7.Management s Discussion and Analysis o...
1200,920760,LEN,10-K,2020-01-27 00:00:00.0,2019-11-30 00:00:00.0,>Item 1A.Risk Factors.The following are what w...,>Item 7.Management s Discussion and Analysis o...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
50,931148,EAF,10-K,2020-02-21 00:00:00.0,2019-12-31 00:00:00.0,">Item 1A.Risk FactorsOur business, financial c...",>Item 7. Management s Discussion and Analysis ...
1407,931148,GTI,10-K,2020-02-21 00:00:00.0,2019-12-31 00:00:00.0,">Item 1A.Risk FactorsOur business, financial c...",>Item 7. Management s Discussion and Analysis ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
438,933136,COOP,10-K,2020-02-28 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk FactorsYou should carefully con...,>Item 7. Management s Discussion and Analysis ...
623,933136,COOP,10-K,2020-02-28 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk FactorsYou should carefully con...,>Item 7. Management s Discussion and Analysis ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
213,945394,SVC,10-K,2020-03-02 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk FactorsOur business is subject ...,>Item 7. Management s Discussion and Analysis ...
284,945394,SVC,10-K,2020-03-02 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk FactorsOur business is subject ...,>Item 7. Management s Discussion and Analysis ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
586,1000753,NSP,10-K,2020-02-12 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors.The statements in this ...,>Item 7. Management s Discussion and Analysis ...
1145,1000753,NSP,10-K,2020-02-12 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors.The statements in this ...,>Item 7. Management s Discussion and Analysis ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
1848,1001907,ASTC,10-K,2020-09-08 00:00:00.0,2020-06-30 00:00:00.0,>Item 1A. Risk Factors An investment in our se...,>Item 7. Management s Discussion and Analysis ...
1856,1001907,ASTC,10-K,2020-09-08 00:00:00.0,2020-06-30 00:00:00.0,>Item 1A. Risk Factors An investment in our se...,>Item 7. Management s Discussion and Analysis ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
1167,1004155,AGL,10-K,2020-02-20 00:00:00.0,2019-12-31 00:00:00.0,>Item 1ARisk FactorsI-17,>Item 7.MANAGEMENT'S DISCUSSION AND ANALYSIS O...
1392,1004155,GAS,10-K,2020-02-20 00:00:00.0,2019-12-31 00:00:00.0,>Item 1ARisk FactorsI-17,>Item 7.MANAGEMENT'S DISCUSSION AND ANALYSIS O...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
283,1006837,HCHC,10-K,2020-03-16 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORSThe following risk facto...,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...
1445,1006837,HCHC,10-K,2020-03-16 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORSThe following risk facto...,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
1841,1010470,PROV,10-K,2020-09-04 00:00:00.0,2020-06-30 00:00:00.0,>Item 1A. Risk Factors We assume and manage a ...,>Item 7. Management s Discussion and Analysis ...
1857,1010470,PROV,10-K,2020-09-04 00:00:00.0,2020-06-30 00:00:00.0,>Item 1A. Risk Factors We assume and manage a ...,>Item 7. Management s Discussion and Analysis ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
610,1012019,RUSHB,10-K,2020-02-26 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors An investment in our co...,>Item 7 Management s Discussion and Analysis o...
1352,1012019,RUSHA,10-K,2020-02-26 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors An investment in our co...,>Item 7 Management s Discussion and Analysis o...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
169,1014739,OPCH,10-K,2020-03-05 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors in this Annual Report....,>Item 7. Management s Discussion and Analysis ...
1073,1014739,OPCH,10-K,2020-03-05 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors in this Annual Report....,>Item 7. Management s Discussion and Analysis ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
1842,1015155,CTHR,10-K,2020-09-04 00:00:00.0,2020-06-30 00:00:00.0,>Item 1A. Risk Factors We operate in a dynamic...,>Item 7. Management s Discussion and Analysis ...
1858,1015155,CTHR,10-K,2020-09-04 00:00:00.0,2020-06-30 00:00:00.0,>Item 1A. Risk Factors We operate in a dynamic...,>Item 7. Management s Discussion and Analysis ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
852,1016169,AIS,10-K,2020-03-03 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. RISK FACTORS The following risk fac...,>Item 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...
963,1016169,ATRS,10-K,2020-03-03 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. RISK FACTORS The following risk fac...,>Item 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
251,1024795,HLIO,10-K,2020-02-25 00:00:00.0,2019-12-28 00:00:00.0,>ITEM 1A. - RISK FACTORS FACTORS INFLUENCING F...,>ITEM 7. MANAGEMENT'S DISCUSSION AND ANALYSIS ...
777,1024795,HLIO,10-K,2020-02-25 00:00:00.0,2019-12-28 00:00:00.0,>ITEM 1A. - RISK FACTORS FACTORS INFLUENCING F...,>ITEM 7. MANAGEMENT'S DISCUSSION AND ANALYSIS ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
1381,1046568,PRDO,10-K,2020-02-19 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. RISK FACTORS Risks Related to the Hi...,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...
1414,1046568,PRDO,10-K,2020-02-19 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. RISK FACTORS Risks Related to the Hi...,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
751,1059262,SP,10-K,2020-02-20 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk FactorsThe following discussion...,>Item 7. Management's Discussion and Analysis ...
932,1059262,SP,10-K,2020-02-20 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk FactorsThe following discussion...,>Item 7. Management's Discussion and Analysis ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
272,1075415,DHC,10-K,2020-03-02 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors.Our business is subject...,>Item 7. Management's Discussion and Analysis ...
1142,1075415,DHC,10-K,2020-03-02 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors.Our business is subject...,>Item 7. Management's Discussion and Analysis ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
113,1114483,GB,10-K,2020-02-20 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORS Our business faces many...,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...
303,1114483,ITGR,10-K,2020-02-20 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORS Our business faces many...,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
806,1124105,CBIO,10-K,2020-02-20 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. RISK FACTORS The following section i...,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...
1177,1124105,CBIO,10-K,2020-02-20 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. RISK FACTORS The following section i...,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
310,1137774,PRU,10-K,2020-02-14 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A.RISK FACTORS You should carefully con...,>ITEM 7.MANAGEMENT S DISCUSSION AND ANALYSIS O...
353,1137774,PRU,10-K,2020-02-14 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A.RISK FACTORS You should carefully con...,>ITEM 7.MANAGEMENT S DISCUSSION AND ANALYSIS O...
356,1137774,PRS,10-K,2020-02-14 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A.RISK FACTORS You should carefully con...,>ITEM 7.MANAGEMENT S DISCUSSION AND ANALYSIS O...
913,1137774,PRS,10-K,2020-02-14 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A.RISK FACTORS You should carefully con...,>ITEM 7.MANAGEMENT S DISCUSSION AND ANALYSIS O...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
1661,1137789,STX,10-K,2020-08-10 00:00:00.0,2020-07-03 00:00:00.0,>ITEM 1A.RISK FACTORSThe ongoing COVID-19 pand...,>ITEM 7. MANAGEMENT'S DISCUSSION AND ANALYSIS ...
1799,1137789,STX,10-K,2020-08-07 00:00:00.0,2020-07-03 00:00:00.0,>ITEM 1A.RISK FACTORSThe ongoing COVID-19 pand...,>ITEM 7. MANAGEMENT'S DISCUSSION AND ANALYSIS ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
530,1157601,SNTA,10-K,2020-02-26 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors You should carefully co...,>Item 7. Management s Discussion and Analysis ...
1000,1157601,MDGL,10-K,2020-02-26 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors You should carefully co...,>Item 7. Management s Discussion and Analysis ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
595,1210708,HSON,10-K,2020-03-31 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORSThe following risk facto...,>ITEM 7.MANAGEMENT S DISCUSSION AND ANALYSIS O...
1190,1210708,HSON,10-K,2020-03-31 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORSThe following risk facto...,>ITEM 7.MANAGEMENT S DISCUSSION AND ANALYSIS O...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
367,1230245,PIPR,10-K,2020-02-28 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORS. In the normal course o...,>ITEM 7. MANAGEMENT'S DISCUSSION AND ANALYSIS ...
1220,1230245,PIPR,10-K,2020-02-28 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORS. In the normal course o...,>ITEM 7. MANAGEMENT'S DISCUSSION AND ANALYSIS ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
1653,1230524,CETC,10-K,2020-08-07 00:00:00.0,2020-07-31 00:00:00.0,>Item 1A. Risk Factors. Not applicable.,>Item 7. Management s Discussion and Analysis ...
1698,1230524,CETC,10-K/A,2020-08-13 00:00:00.0,2020-07-31 00:00:00.0,>Item 1A. Risk Factors. Not applicable.,>Item 7. Management s Discussion and Analysis ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
54,1280776,VTL,10-K,2020-03-16 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors. Investing in our commo...,>Item 7. Management s Discussion and Analysis ...
79,1280776,IMUX,10-K,2020-03-16 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors. Investing in our commo...,>Item 7. Management s Discussion and Analysis ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
1193,1282648,HK,10-K,2020-03-25 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORS Oil and natural gas pri...,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...
1198,1282648,RAME,10-K,2020-03-25 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORS Oil and natural gas pri...,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
679,1289945,USMO,10-K,2020-02-27 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORSThe following important ...,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...
983,1289945,SPOK,10-K,2020-02-27 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORSThe following important ...,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
1654,1300938,ABCE,10-K,2020-08-07 00:00:00.0,2019-12-31 00:00:00.0,">ITEM 1A. RISK FACTORS See below. Otherwise, n...",>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...
1927,1300938,ABCE,10-K/A,2020-09-16 00:00:00.0,2019-12-31 00:00:00.0,">ITEM 1A. RISK FACTORS See below. Otherwise, n...",>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
1843,1307624,HYBG,10-K,2020-09-04 00:00:00.0,2020-06-30 00:00:00.0,>Item 1A. Risk Factors As a smaller reporting ...,>Item 7. Management s Discussion and Analysis ...
1861,1307624,HYBG,10-K,2020-09-04 00:00:00.0,2020-06-30 00:00:00.0,>Item 1A. Risk Factors As a smaller reporting ...,>Item 7. Management s Discussion and Analysis ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
698,1326190,ALT,10-K,2020-03-27 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors. In addition to the oth...,>Item 7. Management s Discussion and Analysis ...
1373,1326190,PIP,10-K,2020-03-27 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors. In addition to the oth...,>Item 7. Management s Discussion and Analysis ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
1844,1327567,PANW,10-K,2020-09-04 00:00:00.0,2020-07-31 00:00:00.0,>ITEM 1A. RISK FACTORSOur operations and finan...,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...
1862,1327567,PANW,10-K,2020-09-04 00:00:00.0,2020-07-31 00:00:00.0,>ITEM 1A. RISK FACTORSOur operations and finan...,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
240,1355096,LINTA,10-K,2020-02-26 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors The risks described bel...,>Item 7. Management's Discussion and Analysis ...
836,1355096,LCAPA,10-K,2020-02-26 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors The risks described bel...,>Item 7. Management's Discussion and Analysis ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
29,1356090,PGEN,10-K,2020-03-02 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A.Risk FactorsInvesting in our common s...,>Item 7.Management's Discussion and Analysis o...
1498,1356090,PGEN,10-K,2020-03-02 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A.Risk FactorsInvesting in our common s...,>Item 7.Management's Discussion and Analysis o...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
155,1357878,PEPT,10-K,2020-06-23 00:00:00.0,2020-03-31 00:00:00.0,>ITEM 1A. RISK FACTORS. The Company will face ...,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...
1673,1357878,PEPT,10-K/A,2020-08-11 00:00:00.0,2020-03-31 00:00:00.0,>ITEM 1A. RISK FACTORS. The Company will face ...,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
1552,1397795,QUTR,10-K,2020-07-21 00:00:00.0,2020-04-30 00:00:00.0,>Item 1A. Risk Factors As a smaller reporting...,>Item 7. Management s Discussion and Analysis ...
1961,1397795,QUTR,10-K/A,2020-09-23 00:00:00.0,2020-04-30 00:00:00.0,>Item 1A. Risk Factors As a smaller reporting...,>Item 7. Management s Discussion and Analysis ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
465,1403853,NES,10-K,2020-03-10 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk FactorsThis section describes m...,>Item 7. Management s Discussion and Analysis ...
1418,1403853,NES,10-K,2020-03-10 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk FactorsThis section describes m...,>Item 7. Management s Discussion and Analysis ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
241,1404281,NVUS,10-K,2020-03-17 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors. An investment in share...,>ITEM 7. Management s Discussion and Analysis ...
1134,1404281,TKAI,10-K,2020-03-17 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors. An investment in share...,>ITEM 7. Management s Discussion and Analysis ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
1,1429260,FBIO,10-K,2020-03-16 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk factors Investing in our Common...,>Item 7. Management s Discussion and Analysis ...
313,1429260,FBIO,10-K,2020-03-16 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk factors Investing in our Common...,>Item 7. Management s Discussion and Analysis ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
764,1455863,COLD,10-K,2020-03-02 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. Risk Factors Set forth below are cer...,>ITEM 7. Management s Discussion and Analysis ...
1482,1455863,COLD,10-K,2020-03-02 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. Risk Factors Set forth below are cer...,>ITEM 7. Management s Discussion and Analysis ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
131,1456772,OPI,10-K,2020-02-20 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk FactorsOur business is subject ...,>Item 7. Management s Discussion and Analysis ...
606,1456772,OPI,10-K,2020-02-20 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk FactorsOur business is subject ...,>Item 7. Management s Discussion and Analysis ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
8,1472595,AH,10-K,2020-02-20 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A.Risk FactorsRisks Relating to our Bus...,>Item 7.Management s Discussion and Analysis o...
868,1472595,RCM,10-K,2020-02-20 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A.Risk FactorsRisks Relating to our Bus...,>Item 7.Management s Discussion and Analysis o...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
146,1492691,SWFT,10-K,2020-02-27 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A.RISK FACTORSWhen evaluating our compa...,>ITEM 7.MANAGEMENT'S DISCUSSION AND ANALYSIS O...
1390,1492691,KNX,10-K,2020-02-27 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A.RISK FACTORSWhen evaluating our compa...,>ITEM 7.MANAGEMENT'S DISCUSSION AND ANALYSIS O...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
759,1496048,GGP,10-K,2020-02-28 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORSYou should carefully con...,>ITEM 7. MANAGEMENT'S DISCUSSION AND ANALYSIS ...
904,1496048,GGP,10-K,2020-02-28 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORSYou should carefully con...,>ITEM 7. MANAGEMENT'S DISCUSSION AND ANALYSIS ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
1613,1498148,NONE,10-K,2020-07-28 00:00:00.0,2020-02-29 00:00:00.0,>Item 1A. Risk Factors 8,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...
1632,1498148,AITX,10-K/A,2020-07-31 00:00:00.0,2020-02-29 00:00:00.0,>Item 1A. Risk Factors 8,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
156,1501697,ASNS,10-K,2020-03-12 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORSAn investment in shares ...,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...
790,1501697,ASNS,10-K,2020-03-12 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORSAn investment in shares ...,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
633,1527469,ATH,10-K,2020-02-20 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors Risks Relating to Insur...,>Item 7. Management s Discussion and Analysis ...
696,1527469,AHL,10-K,2020-02-20 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors Risks Relating to Insur...,>Item 7. Management s Discussion and Analysis ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
537,1527590,RC,10-K,2020-03-12 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors Our business and operat...,>Item 7. Management s Discussion and Analysis ...
1213,1527590,RC,10-K,2020-03-12 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors Our business and operat...,>Item 7. Management s Discussion and Analysis ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
635,1530766,BSGM,10-K,2020-03-13 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A RISK FACTORS RISK FACTORS There are...,>Item 7. Management s Discussion and Analysis ...
1075,1530766,BIOS,10-K,2020-03-13 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A RISK FACTORS RISK FACTORS There are...,>Item 7. Management s Discussion and Analysis ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
1059,1533924,AMPY,10-K,2020-03-05 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORS Our business and operat...,>Item 7. Management s Discussion and Analysis ...
1080,1533924,AMPY,10-K,2020-03-05 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORS Our business and operat...,>Item 7. Management s Discussion and Analysis ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
1665,1538495,ETST,10-K,2020-08-10 00:00:00.0,2020-03-31 00:00:00.0,>ITEM 1A. RISK FACTORS This investment has a h...,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...
1730,1538495,ETST,10-K/A,2020-08-18 00:00:00.0,2020-03-31 00:00:00.0,>ITEM 1A. RISK FACTORS This investment has a h...,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
1294,1544227,MLND,10-K,2020-03-11 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORSYou should carefully con...,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...
1345,1544227,MLND,10-K,2020-03-11 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORSYou should carefully con...,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
1264,1553404,PGTK,10-K,2020-07-14 00:00:00.0,2020-03-31 00:00:00.0,>Item 1A. Risk Factors Risks Related to our Bu...,>Item 7. Management s Discussion and Analysis ...
1607,1553404,PGTK,10-K/A,2020-07-27 00:00:00.0,2020-03-31 00:00:00.0,>Item 1A. Risk Factors Risks Related to our Bu...,>Item 7. Management s Discussion and Analysis ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
362,1560385,LMCA,10-K,2020-02-26 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors.An investment in our co...,>Item 7. Management s Discussion and Analysis ...
1509,1560385,LMCK,10-K,2020-02-26 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors.An investment in our co...,>Item 7. Management s Discussion and Analysis ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
178,1561387,BFYT,10-K,2020-03-04 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORS In addition to the othe...,>ITEM 7. MANAGEMENT'S DISCUSSION AND ANALYSIS ...
1110,1561387,BFYT,10-K,2020-03-04 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORS In addition to the othe...,>ITEM 7. MANAGEMENT'S DISCUSSION AND ANALYSIS ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
203,1567683,CWEN,10-K,2020-03-02 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A Risk FactorsRisks related to the PG...,>Item 7 Management's Discussion and Analysis...
1457,1567683,CWEN,10-K,2020-03-02 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A Risk FactorsRisks related to the PG...,>Item 7 Management's Discussion and Analysis...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
1845,1568875,ZNRG,10-K,2020-09-04 00:00:00.0,2018-12-31 00:00:00.0,>Item 1A. Risk Factors 7,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...
1863,1568875,ZNRG,10-K/A,2020-09-04 00:00:00.0,2018-12-31 00:00:00.0,>Item 1A. Risk Factors 7,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
41,1570132,ANVI,10-K,2020-07-06 00:00:00.0,2020-02-29 00:00:00.0,>Item 1A. Risk Factors. 2,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...
1557,1570132,ANVI,10-K/A,2020-07-20 00:00:00.0,2020-02-29 00:00:00.0,>Item 1A. Risk Factors. 2,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
1628,1575345,NONE,10-K,2020-07-30 00:00:00.0,2020-04-30 00:00:00.0,>Item 1A. RISK FACTORS 3,>Item 7. Management s Discussion and Analysis ...
1633,1575345,NONE,10-K,2020-07-30 00:00:00.0,2020-04-30 00:00:00.0,>Item 1A. RISK FACTORS 3,>Item 7. Management s Discussion and Analysis ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
646,1578845,ACT,10-K,2020-02-18 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORS CAUTIONARY NOTE REGARDI...,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...
1151,1578845,ACT,10-K,2020-02-18 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORS CAUTIONARY NOTE REGARDI...,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
385,1579684,GCI,10-K,2020-03-02 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORS You should carefully co...,>ITEM 7. MANAGEMENT'S DISCUSSION AND ANALYSIS ...
1364,1579684,GCI,10-K,2020-03-02 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORS You should carefully co...,>ITEM 7. MANAGEMENT'S DISCUSSION AND ANALYSIS ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
1649,1580149,BIVI,10-K,2020-08-06 00:00:00.0,2020-06-30 00:00:00.0,">ITEM 1A. RISK FACTORS Our business, financial...",>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...
1656,1580149,BIVI,10-K/A,2020-08-07 00:00:00.0,2020-06-30 00:00:00.0,">ITEM 1A. RISK FACTORS Our business, financial...",>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
323,1590714,ESI,10-K,2020-02-28 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk FactorsThe ownership of our sec...,>Item 7. Management s Discussion and Analysis ...
894,1590714,ESI,10-K,2020-02-28 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk FactorsThe ownership of our sec...,>Item 7. Management s Discussion and Analysis ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
1666,1591698,PCTY,10-K,2020-08-10 00:00:00.0,2020-06-30 00:00:00.0,">Item 1A. Risk Factors. Our business, prospect...",>Item 7. Management s Discussion and Analysis ...
1818,1591698,PCTY,10-K,2020-08-07 00:00:00.0,2020-06-30 00:00:00.0,">Item 1A. Risk Factors. Our business, prospect...",>Item 7. Management s Discussion and Analysis ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
732,1593195,TPUB,10-K,2020-03-11 00:00:00.0,2019-12-29 00:00:00.0,>Item 1A. Risk FactorsInvestors should careful...,>Item 7. Management s Discussion and Analysis ...
768,1593195,TPUB,10-K,2020-03-11 00:00:00.0,2019-12-29 00:00:00.0,>Item 1A. Risk FactorsInvestors should careful...,>Item 7. Management s Discussion and Analysis ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
684,1599947,SUNE,10-K,2020-03-17 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors. Risks Related to our R...,>Item 7. Management s Discussion and Analysis ...
1002,1599947,SUNE,10-K,2020-03-17 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors. Risks Related to our R...,>Item 7. Management s Discussion and Analysis ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
824,1600470,MR,10-K,2020-03-10 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. RISK FACTORS Our business involves a...,>Item 7. Management s Discussion and Analysis ...
1527,1600470,MR,10-K,2020-03-10 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. RISK FACTORS Our business involves a...,>Item 7. Management s Discussion and Analysis ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
13,1611983,LBRDA,10-K,2020-02-03 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors The risks described bel...,>Item 7. Management's Discussion and Analysis ...
122,1611983,LBRDK,10-K,2020-02-03 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors The risks described bel...,>Item 7. Management's Discussion and Analysis ...
470,1611983,LBRDA,10-K,2020-02-03 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors The risks described bel...,>Item 7. Management's Discussion and Analysis ...
1366,1611983,LBRDK,10-K,2020-02-03 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors The risks described bel...,>Item 7. Management's Discussion and Analysis ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
112,1623925,AM,10-K,2020-02-12 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors We are subject to certa...,>Item 7.Management s Discussion and Analysis o...
494,1623925,AM,10-K,2020-02-12 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors We are subject to certa...,>Item 7.Management s Discussion and Analysis o...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
150,1627014,BKI,10-K,2020-02-28 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors In addition to the norm...,>Item 7.Management's Discussion and Analysis o...
515,1627014,BKFS,10-K,2020-02-28 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors In addition to the norm...,>Item 7.Management's Discussion and Analysis o...
1178,1627014,BKI,10-K,2020-02-28 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors In addition to the norm...,>Item 7.Management's Discussion and Analysis o...
1495,1627014,BKFS,10-K,2020-02-28 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors In addition to the norm...,>Item 7.Management's Discussion and Analysis o...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
1966,1627452,MEPW,10-K,2020-09-23 00:00:00.0,2017-12-31 00:00:00.0,>ITEM 1A. RISK FACTORS RISKS RELATED TO OUR BU...,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...
1977,1627452,MEPW,10-K,2020-09-24 00:00:00.0,2018-12-31 00:00:00.0,>ITEM 1A. RISK FACTORS RISKS RELATED TO OUR BU...,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
46,1652044,GOOGL,10-K,2020-02-04 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A.RISK FACTORSOur operations and financ...,>ITEM 7.MANAGEMENT S DISCUSSION AND ANALYSIS O...
151,1652044,GOOG,10-K,2020-02-04 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A.RISK FACTORSOur operations and financ...,>ITEM 7.MANAGEMENT S DISCUSSION AND ANALYSIS O...
1163,1652044,GOOGL,10-K,2020-02-04 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A.RISK FACTORSOur operations and financ...,>ITEM 7.MANAGEMENT S DISCUSSION AND ANALYSIS O...
1397,1652044,GOOG,10-K,2020-02-04 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A.RISK FACTORSOur operations and financ...,>ITEM 7.MANAGEMENT S DISCUSSION AND ANALYSIS O...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
780,1666700,DD,10-K,2020-02-14 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORSThe Company's operations...,>ITEM 7. MANAGEMENT'S DISCUSSION AND ANALYSIS ...
1186,1666700,DD,10-K,2020-02-14 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORSThe Company's operations...,>ITEM 7. MANAGEMENT'S DISCUSSION AND ANALYSIS ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
664,1668428,FG,10-K,2020-03-02 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk FactorsIn addition to the other...,>Item 7. Management s Discussion and Analysis ...
707,1668428,FGL,10-K,2020-03-02 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk FactorsIn addition to the other...,>Item 7. Management s Discussion and Analysis ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
1246,1675820,ROVI,10-K,2020-02-18 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORSInvesting in our common ...,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...
1419,1675820,TIVO,10-K,2020-02-18 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORSInvesting in our common ...,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
402,1679688,CLNS,10-K,2020-03-02 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors. The following risk fac...,>Item 7. Management s Discussion and Analysis ...
1004,1679688,CLNS,10-K,2020-03-02 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors. The following risk fac...,>Item 7. Management s Discussion and Analysis ...
1367,1679688,CLNY,10-K,2020-03-02 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors. The following risk fac...,>Item 7. Management s Discussion and Analysis ...
1532,1679688,CLNY,10-K,2020-03-02 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors. The following risk fac...,>Item 7. Management s Discussion and Analysis ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
1139,1688476,NEX,10-K,2020-03-12 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk FactorsRISK FACTORS An investme...,>Item 7. Management's Discussion and Analysis ...
1337,1688476,NEX,10-K,2020-03-12 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk FactorsRISK FACTORS An investme...,>Item 7. Management's Discussion and Analysis ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
740,1690666,TSRA,10-K,2020-02-18 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors Our operations and fina...,>Item 7. Management s Discussion and Analysis ...
1245,1690666,XPER,10-K,2020-02-18 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors Our operations and fina...,>Item 7. Management s Discussion and Analysis ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
467,1701605,BHI,10-K,2020-02-13 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORSAn investment in our com...,>ITEM 7. MANAGEMENT'S DISCUSSION AND ANALYSIS ...
488,1701605,BHGE,10-K,2020-02-13 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORSAn investment in our com...,>ITEM 7. MANAGEMENT'S DISCUSSION AND ANALYSIS ...
1092,1701605,BHI,10-K,2020-02-13 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORSAn investment in our com...,>ITEM 7. MANAGEMENT'S DISCUSSION AND ANALYSIS ...
1319,1701605,BHGE,10-K,2020-02-13 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORSAn investment in our com...,>ITEM 7. MANAGEMENT'S DISCUSSION AND ANALYSIS ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
987,1707925,LIN,10-K,2020-03-02 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORS Due to the size and geo...,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...
1338,1707925,LIN,10-K,2020-03-02 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORS Due to the size and geo...,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
1741,1709542,CIK0001709542,10-K/A,2020-08-19 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORS. As a smaller reportin...,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...
1935,1709542,CIK0001709542,10-K/A,2020-08-19 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORS. As a smaller reportin...,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
175,1712184,LILAK,10-K,2020-02-19 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A.RISK FACTORS In addition to the other...,>Item 7 - Management s Discussion and Analysis...
436,1712184,LILAK,10-K,2020-02-19 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A.RISK FACTORS In addition to the other...,>Item 7 - Management s Discussion and Analysis...
1331,1712184,LILA,10-K,2020-02-19 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A.RISK FACTORS In addition to the other...,>Item 7 - Management s Discussion and Analysis...
1353,1712184,LILA,10-K,2020-02-19 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A.RISK FACTORS In addition to the other...,>Item 7 - Management s Discussion and Analysis...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
111,1723128,IPXL,10-K,2020-03-02 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors An investment in our co...,>Item 7. Management s Discussion and Analysis ...
1302,1723128,AMRX,10-K,2020-03-02 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors An investment in our co...,>Item 7. Management s Discussion and Analysis ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
117,1726173,BH,10-K,2020-02-24 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors Biglari Holdings and it...,>Item 7.Management s Discussion and Analysis o...
837,1726173,BH.A,10-K,2020-02-24 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors Biglari Holdings and it...,>Item 7.Management s Discussion and Analysis o...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
394,1733998,NWN,10-K,2020-03-02 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORSNW Holdings and NW Natu...,>ITEM 7. MANAGEMENT'S DISCUSSION AND ANALYSIS ...
1332,1733998,NWN,10-K,2020-03-02 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORSNW Holdings and NW Natu...,>ITEM 7. MANAGEMENT'S DISCUSSION AND ANALYSIS ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
1707,1740797,NONE,10-K,2020-08-13 00:00:00.0,2020-03-31 00:00:00.0,>Item 1A. Risk Factors. 5,>Item 7. Management's Discussion and Analysis ...
1718,1740797,NONE,10-K/A,2020-08-14 00:00:00.0,2020-03-31 00:00:00.0,>Item 1A. Risk Factors. 5,>Item 7. Management's Discussion and Analysis ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
1008,1756640,WGL,10-K,2020-05-12 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors You should carefully co...,>Item 7. Management s Discussion and Analysis ...
1637,1756640,WISM,10-K/A,2020-08-04 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors You should carefully co...,>Item 7. Management s Discussion and Analysis ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
1847,1761696,CIK0001761696,10-K,2020-09-04 00:00:00.0,2020-03-31 00:00:00.0,>ITEM 1A. RISK FACTORS. Investing in our commo...,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...
1867,1761696,CIK0001761696,10-K,2020-09-04 00:00:00.0,2020-03-31 00:00:00.0,>ITEM 1A. RISK FACTORS. Investing in our commo...,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
795,1790982,ARNC,10-K,2020-03-30 00:00:00.0,2019-12-31 00:00:00.0,">Item 1A. Risk Factors. Our business, financia...",>Item 7. Management s Discussion and Analysis ...
1306,1790982,ARNC,10-K,2020-03-30 00:00:00.0,2019-12-31 00:00:00.0,">Item 1A. Risk Factors. Our business, financia...",>Item 7. Management s Discussion and Analysis ...

In [43]:
""" Expanding on the  cell output above """
def has_same_column(group, col, label="This group"):
    if col == "filing":
        col_num = 3
    elif col == "1a":
        col_num = 5
    elif col == "7":
        col_num = 6
        
    unique_rows = len(np.unique((group.iloc[:,col_num])))
    if unique_rows == 1:
        display(label + " has copies in column " + col)
        
    else:
        display(label + " has {} different values for column ".format(unique_rows) + col)
    
    

""" Same cik, different tickers. Same filing date. Same text for 1/7 between the tickers.
Maybe in this case they changed their name and filed it twice?"""
grp = groups.get_group(9346)
display(grp)
has_same_column(grp, "1a", "9346")
has_same_column(grp, "7", "9346")
has_same_column(grp, "filing", "9346")

""" Same deal here as above, except filing date for 2nd is later and its a 10-K/A"""
grp = groups.get_group(1756640)
display(grp)
has_same_column(grp, "1a", "1756640")
has_same_column(grp, "7", "1756640")
has_same_column(grp, "filing", "1756640")

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
341,9346,PTVCB,10-K,2020-03-06 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. RISK FACTORS The following is a desc...,>Item 7. MANAGEMENT'S DISCUSSION AND ANALYSIS ...
854,9346,BWINB,10-K,2020-03-06 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. RISK FACTORS The following is a desc...,>Item 7. MANAGEMENT'S DISCUSSION AND ANALYSIS ...

'9346 has copies in column 1a'

'9346 has copies in column 7'

'9346 has copies in column filing'

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
1008,1756640,WGL,10-K,2020-05-12 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors You should carefully co...,>Item 7. Management s Discussion and Analysis ...
1637,1756640,WISM,10-K/A,2020-08-04 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors You should carefully co...,>Item 7. Management s Discussion and Analysis ...

'1756640 has copies in column 1a'

'1756640 has copies in column 7'

'1756640 has 2 different values for column filing'

In [21]:
## Look at a particular example, PG
df_2020_pg = df_2020.loc[df_2020['ticker'] == "PG"]
display(df_2020_pg)

#1a and 7 are the same across rows
display(df_2020_pg.iloc[0,5] == df_2020_pg.iloc[1,5] == df_2020_pg.iloc[2,5])
display(df_2020_pg.iloc[0,6] == df_2020_pg.iloc[1,6] == df_2020_pg.iloc[2,6])

"""
Perhaps we need to remove duplicates --> The only different b/t these are filing_date and form_type
-> Wouldn't we expect the 10-K/A to have either content to append to the 1a/7 sections (short section) or a
revised version of the entire thing. Perhaps this means that the content of the 10-K in the first row
was overwritten by the new version. Maybe we can reduce this to 1 row and add some sort of a feature that this
required ammendments (or how far in the future the last amendment was made, etc)
-> If we reduce to 1 row, do we put the filing data as the first, last, or an avrg of the two dates or something?
"""

# Take most recent, unless N/A

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
1643,80424,PG,10-K,2020-08-06 00:00:00.0,2020-06-30 00:00:00.0,>Item 1A. Risk Factors.We discuss our expectat...,>Item 7. Management's Discussion and Analysis ...
1657,80424,PG,10-K/A,2020-08-10 00:00:00.0,2020-06-30 00:00:00.0,>Item 1A. Risk Factors.We discuss our expectat...,>Item 7. Management's Discussion and Analysis ...
1771,80424,PG,10-K/A,2020-08-07 00:00:00.0,2020-06-30 00:00:00.0,>Item 1A. Risk Factors.We discuss our expectat...,>Item 7. Management's Discussion and Analysis ...

True

True

'\nPerhaps we need to remove duplicates --> Confused why there are 10-K/A \n'

# Group by Ticker

In [24]:
""" Group by ticker, print if the CIK doesn't match"""
groups_ticker = df_2020.groupby("ticker")
for key, group in groups_ticker:
    if len(np.unique((group.iloc[:,0]))) > 1:
        display(group)
        
""" Seems like we have lots of differing CIKs for the same ticker. Also some rows with no ticker"""

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
593,1620602,ACT,10-K,2020-02-18 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORS CAUTIONARY NOTE REGARDI...,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...
646,1578845,ACT,10-K,2020-02-18 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORS CAUTIONARY NOTE REGARDI...,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...
1151,1578845,ACT,10-K,2020-02-18 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORS CAUTIONARY NOTE REGARDI...,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...
1296,1437517,ACT,10-K,2020-04-07 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors The Company qualifies a...,>Item 7. Management s Discussion and Analysis ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
347,4515,AMR,10-K,2020-02-19 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORSBelow are certain risk f...,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...
840,6201,AMR,10-K,2020-02-19 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORSBelow are certain risk f...,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...
1394,1690769,AMR,10-K,2020-03-05 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A.Risk Factors 10,>Item 7. Management s Discussion and Analysis ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
693,4281,ARNC,10-K,2020-02-27 00:00:00.0,2019-12-31 00:00:00.0,">Item 1A. Risk Factors. Arconic s business, fi...",>Item 7. Management s Discussion and Analysis ...
795,1790982,ARNC,10-K,2020-03-30 00:00:00.0,2019-12-31 00:00:00.0,">Item 1A. Risk Factors. Our business, financia...",>Item 7. Management s Discussion and Analysis ...
1306,1790982,ARNC,10-K,2020-03-30 00:00:00.0,2019-12-31 00:00:00.0,">Item 1A. Risk Factors. Our business, financia...",>Item 7. Management s Discussion and Analysis ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
467,1701605,BHI,10-K,2020-02-13 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORSAn investment in our com...,>ITEM 7. MANAGEMENT'S DISCUSSION AND ANALYSIS ...
865,808362,BHI,10-K,2020-02-13 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORSThe following risk facto...,>ITEM 7. MANAGEMENT'S DISCUSSION AND ANALYSIS ...
1092,1701605,BHI,10-K,2020-02-13 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORSAn investment in our com...,>ITEM 7. MANAGEMENT'S DISCUSSION AND ANALYSIS ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
207,18672,CNL,10-K,2020-03-03 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORSThe following risk facto...,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...
565,1089819,CNL,10-K,2020-03-03 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORSThe following risk facto...,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...
901,1684682,CNL,10-K,2020-03-26 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk FactorsInvesting in our shares ...,>Item 7. Management s Discussion and Analysis ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
328,30554,DD,10-K,2020-02-14 00:00:00.0,2019-12-31 00:00:00.0,">ITEM 1A. RISK FACTORS, continued unanticipate...",>ITEM 7. MANAGEMENT'S DISCUSSION AND ANALYSIS ...
780,1666700,DD,10-K,2020-02-14 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORSThe Company's operations...,>ITEM 7. MANAGEMENT'S DISCUSSION AND ANALYSIS ...
1186,1666700,DD,10-K,2020-02-14 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORSThe Company's operations...,>ITEM 7. MANAGEMENT'S DISCUSSION AND ANALYSIS ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
839,787250,DPL,10-K,2020-02-28 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A Risk Factors. For a list of certain...,>Item 7 Management's Discussion and Analysis...
881,27430,DPL,10-K,2020-02-28 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A Risk Factors. For a list of certain...,>Item 7 Management's Discussion and Analysis...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
104,1555082,EPE,10-K,2020-03-25 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORSRisks Related to Our Cha...,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...
1447,1584952,EPE,10-K,2020-03-25 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORSRisks Related to Our Cha...,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
385,1579684,GCI,10-K,2020-03-02 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORS You should carefully co...,>ITEM 7. MANAGEMENT'S DISCUSSION AND ANALYSIS ...
1185,39899,GCI,10-K,2020-03-02 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORSAn investment in our com...,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...
1364,1579684,GCI,10-K,2020-03-02 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORS You should carefully co...,>ITEM 7. MANAGEMENT'S DISCUSSION AND ANALYSIS ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
287,1756574,HART,10-K,2020-02-28 00:00:00.0,2019-10-31 00:00:00.0,>Item 1A. Risk Factors An investment in the Co...,>Item 7. Management s Discussion and Analysis ...
1265,1654948,HART,10-K,2020-04-30 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk FactorsThe following are some o...,>Item 7. Management s Discussion and Analysis ...
1368,1563665,HART,10-K,2020-03-27 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors. The following factors ...,>Item 7. Management s Discussion and Analysis ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
200,1465264,HDS,10-K,2020-03-17 00:00:00.0,2020-02-02 00:00:00.0,>ITEM 1A. RISK FACTORSRisks Relating to Our Bu...,>Item 7. Management s Discussion and Analysis ...
1479,1573097,HDS,10-K,2020-03-17 00:00:00.0,2020-02-02 00:00:00.0,>ITEM 1A. RISK FACTORSRisks Relating to Our Bu...,>Item 7. Management s Discussion and Analysis ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
1553,1428389,NONE,10-K,2020-07-15 00:00:00.0,2020-03-31 00:00:00.0,>Item 1A.Risk Factors Much of the information ...,>Item 7. Management s Discussion and Analysis ...
1555,1512886,NONE,10-K,2020-06-24 00:00:00.0,2020-01-31 00:00:00.0,>ITEM 1A. RISK FACTORS As a smaller reporting ...,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...
1556,1549785,NONE,10-K,2020-06-25 00:00:00.0,2020-03-31 00:00:00.0,">ITEM 1A, RISK FACTORS. (C) ITEM 2, PROPERTIES...",">ITEM 7, MANAGEMENT S DISCUSSION AND ANALYSIS ..."
1559,1602409,NONE,10-K,2020-07-13 00:00:00.0,2020-02-29 00:00:00.0,>ITEM 1A. RISK FACTORS In addition to the info...,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...
1563,1685342,NONE,10-K,2020-06-25 00:00:00.0,2020-03-31 00:00:00.0,">ITEM 1A, RISK FACTORS. (C) ITEM 2, PROPERTIES...",">ITEM 7, MANAGEMENT S DISCUSSION AND ANALYSIS ..."
1566,1696898,NONE,10-K,2020-04-23 00:00:00.0,2020-01-31 00:00:00.0,>Item 1A. Risk Factors Not applicable to small...,>Item 7. Management's Discussion and Analysis ...
1567,1697574,NONE,10-K,2020-06-25 00:00:00.0,2020-03-31 00:00:00.0,">Item 1A, Risk Factors (c) Item 2, Properties ...",">Item 7, Management s Discussion and Analysis ..."
1568,1697884,NONE,10-K,2020-06-09 00:00:00.0,2020-01-31 00:00:00.0,>ITEM 1A. RISK FACTORS Risks Related to Our Co...,>ITEM 7. MANAGEMENT'S DISCUSSION AND ANALYSIS ...
1571,1706612,NONE,10-K,2020-06-25 00:00:00.0,2020-03-31 00:00:00.0,">Item 1A, Risk Factors (c) Item 2, Properties ...",">Item 7, Management s Discussion and Analysis ..."
1573,1710495,NONE,10-K,2020-06-05 00:00:00.0,2020-01-31 00:00:00.0,>Item 1A. Risk Factors Not applicable to small...,>Item 7. Management's Discussion and Analysis ...
1574,1714379,NONE,10-K,2020-03-19 00:00:00.0,2020-01-31 00:00:00.0,>ITEM 1A RISK FACTORS 4,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...
1575,1715362,NONE,10-K,2020-06-25 00:00:00.0,2020-03-31 00:00:00.0,">Item 1A, Risk Factors (c) Item 2, Properties ...",">Item 7, Management s Discussion and Analysis ..."
1577,1721745,NONE,10-K,2020-06-25 00:00:00.0,2020-03-31 00:00:00.0,">Item 1A, Risk Factors (c) Item 2, Properties ...",">Item 7, Management s Discussion and Analysis ..."
1579,1728028,NONE,10-K,2020-06-25 00:00:00.0,2020-03-31 00:00:00.0,">Item 1A, Risk Factors (c) Item 2, Properties ...",">Item 7, Management s Discussion and Analysis ..."
1581,1736790,NONE,10-K,2020-06-25 00:00:00.0,2020-03-31 00:00:00.0,">Item 1A, Risk Factors (c) Item 2, Properties ...",">Item 7, Management s Discussion and Analysis ..."
1582,1742491,NONE,10-K,2020-06-26 00:00:00.0,2020-03-31 00:00:00.0,>ITEM 1A. RISK FACTORS As a smaller reporting...,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...
1584,1745376,NONE,10-K,2020-06-25 00:00:00.0,2020-03-31 00:00:00.0,">Item 1A, Risk Factors (c) Item 2, Properties ...",">Item 7, Management s Discussion and Analysis ..."
1586,1755047,NONE,10-K,2020-06-25 00:00:00.0,2020-03-31 00:00:00.0,">Item 1A, Risk Factors (c) Item 2, Properties ...",">Item 7, Management s Discussion and Analysis ..."
1588,1765556,NONE,10-K,2020-06-25 00:00:00.0,2020-03-31 00:00:00.0,">Item 1A, Risk Factors (c) Item 2, Properties ...",">Item 7, Management s Discussion and Analysis ..."
1590,1773055,NONE,10-K,2020-06-25 00:00:00.0,2020-03-31 00:00:00.0,">Item 1A, Risk Factors (c) Item 2, Properties ...",">Item 7, Management s Discussion and Analysis ..."
1592,1784183,NONE,10-K,2020-06-25 00:00:00.0,2020-03-31 00:00:00.0,">Item 1A, Risk Factors (c) Item 2, Properties ...",">Item 7, Management s Discussion and Analysis ..."
1594,1792159,NONE,10-K,2020-06-25 00:00:00.0,2020-03-31 00:00:00.0,">Item 1A, Risk Factors (c) Item 2, Properties ...",">Item 7, Management s Discussion and Analysis ..."
1596,1799186,NONE,10-K,2020-06-25 00:00:00.0,2020-03-31 00:00:00.0,">Item 1A, Risk Factors (c) Item 2, Properties ...",">Item 7, Management s Discussion and Analysis ..."
1613,1498148,NONE,10-K,2020-07-28 00:00:00.0,2020-02-29 00:00:00.0,>Item 1A. Risk Factors 8,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...
1628,1575345,NONE,10-K,2020-07-30 00:00:00.0,2020-04-30 00:00:00.0,>Item 1A. RISK FACTORS 3,>Item 7. Management s Discussion and Analysis ...
1633,1575345,NONE,10-K,2020-07-30 00:00:00.0,2020-04-30 00:00:00.0,>Item 1A. RISK FACTORS 3,>Item 7. Management s Discussion and Analysis ...
1678,1696411,NONE,10-K,2020-08-11 00:00:00.0,2018-12-31 00:00:00.0,>ITEM 1A Risk Factors 6 ITEM 2 Description of ...,>Item 7. Management's Discussion and Analysis ...
1707,1740797,NONE,10-K,2020-08-13 00:00:00.0,2020-03-31 00:00:00.0,>Item 1A. Risk Factors. 5,>Item 7. Management's Discussion and Analysis ...
1716,1355677,NONE,10-K,2020-08-14 00:00:00.0,2020-03-31 00:00:00.0,>Item 1A. Risk Factors As a smaller reporting ...,>Item 7. Management s Discussion and Analysis ...
1718,1740797,NONE,10-K/A,2020-08-14 00:00:00.0,2020-03-31 00:00:00.0,>Item 1A. Risk Factors. 5,>Item 7. Management's Discussion and Analysis ...
1721,1049011,NONE,10-K/A,2020-08-17 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORS An investment in our co...,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...
1759,1128252,NONE,10-K,2020-08-24 00:00:00.0,2010-12-31 00:00:00.0,>Item 1A Risk Factors 7 Item IB Unresolved Sta...,>Item 7. Management s Discussion and Analysis ...
1802,1287032,NONE,10-K,2020-08-26 00:00:00.0,2020-06-30 00:00:00.0,>Item 1A. Risk FactorsYou should carefully con...,>Item 7. Management s Discussion and Analysis ...
1810,1521945,NONE,10-K,2020-08-27 00:00:00.0,2020-06-30 00:00:00.0,>Item 1A. Risk Factors Investing in our common...,>Item 7: Management s Discussion and Analysis ...
1816,1581545,NONE,10-K/A,2020-08-31 00:00:00.0,2019-06-30 00:00:00.0,">Item 1A. Risk Factors. The Company, as a smal...",>Item 7. Management s Discussion and Analysis ...
1859,1115864,NONE,10-K,2020-09-09 00:00:00.0,2004-12-31 00:00:00.0,>Item 1A. Risk Factors Smaller reporting compa...,>Item 7. Management s Discussion and Analysis ...
1877,1720749,NONE,10-K/A,2020-09-10 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A Risk Factors. (C) Item 2 Properties. ...,>Item 7 Management s Discussion and Analysis o...
1879,1756401,NONE,10-K/A,2020-09-10 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A Risk Factors. (C) Item 2 Properties. ...,>Item 7 Management s Discussion and Analysis o...
1915,1667615,NONE,10-K,2020-09-14 00:00:00.0,2020-05-31 00:00:00.0,>Item 1A. Risk Factors. Smaller reporting comp...,>Item 7. Management s Discussion and Analysis ...
1930,1700844,NONE,10-K,2020-09-16 00:00:00.0,2020-08-31 00:00:00.0,>ITEM 1A. RISK FACTORS Not applicable.,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...
1950,1550913,NONE,10-K,2020-09-21 00:00:00.0,2020-06-30 00:00:00.0,>Item 1A. Risk Factors 7,>Item 7. Management s Discussion and Analysis ...
1957,1578348,NONE,10-K,2020-09-22 00:00:00.0,2020-06-30 00:00:00.0,>Item 1A. Risk Factors Investing in our securi...,>Item 7. Management s Discussion and Analysis ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
1542,17313,NO_TICKER,10-K,2020-06-02 00:00:00.0,2020-03-31 00:00:00.0,>Item 1A. Risk FactorsInvesting in our securit...,>Item 7. Management s Discussion and Analysis ...
1548,1278752,NO_TICKER,10-K,2020-05-21 00:00:00.0,2020-03-31 00:00:00.0,>Item 1A. Risk FactorsInvesting in Apollo Inve...,>Item 7. Management s Discussion and Analysis ...
1549,1321741,NO_TICKER,10-K,2020-05-12 00:00:00.0,2020-03-31 00:00:00.0,>ITEM 1A. RISK FACTORS You should carefully co...,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...
1550,1377936,NO_TICKER,10-K,2020-05-06 00:00:00.0,2020-02-29 00:00:00.0,>ITEM 1A. RISK FACTORS Investing in our securi...,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...
1561,1671212,NO_TICKER,10-K,2020-05-21 00:00:00.0,2020-02-29 00:00:00.0,>Item 1A.Risk Factors.Item 2.Properties.,>Item 7.Management's Discussion and Analysis o...
1562,1678507,NO_TICKER,10-K,2020-05-21 00:00:00.0,2020-02-29 00:00:00.0,>Item 1A.Risk Factors.Item 2.Properties.,>Item 7.Management's Discussion and Analysis o...
1564,1686277,NO_TICKER,10-K,2020-05-21 00:00:00.0,2020-02-29 00:00:00.0,>Item 1A.Risk Factors.Item 2.Properties.,>Item 7.Management's Discussion and Analysis o...
1565,1693819,NO_TICKER,10-K,2020-05-21 00:00:00.0,2020-02-29 00:00:00.0,>Item 1A.Risk Factors.Item 2.Properties.,>Item 7.Management's Discussion and Analysis o...
1569,1702777,NO_TICKER,10-K,2020-05-21 00:00:00.0,2020-02-29 00:00:00.0,>Item 1A.Risk Factors.Item 2.Properties.,>Item 7.Management's Discussion and Analysis o...
1572,1710329,NO_TICKER,10-K,2020-05-21 00:00:00.0,2020-02-29 00:00:00.0,>Item 1A.Risk Factors.Item 2.Properties.,>Item 7.Management's Discussion and Analysis o...
1576,1718592,NO_TICKER,10-K,2020-05-21 00:00:00.0,2020-02-29 00:00:00.0,>Item 1A.Risk Factors.Item 2.Properties.,>Item 7.Management's Discussion and Analysis o...
1578,1725618,NO_TICKER,10-K,2020-05-21 00:00:00.0,2020-02-29 00:00:00.0,>Item 1A.Risk Factors.Item 2.Properties.,>Item 7.Management's Discussion and Analysis o...
1580,1734850,NO_TICKER,10-K,2020-05-21 00:00:00.0,2020-02-29 00:00:00.0,>Item 1A.Risk Factors.Item 2.Properties.,>Item 7.Management's Discussion and Analysis o...
1583,1742867,NO_TICKER,10-K,2020-05-21 00:00:00.0,2020-02-29 00:00:00.0,>Item 1A.Risk Factors.Item 2.Properties.,>Item 7.Management's Discussion and Analysis o...
1585,1754008,NO_TICKER,10-K,2020-05-21 00:00:00.0,2020-02-29 00:00:00.0,>Item 1A.Risk Factors.Item 2.Properties.,>Item 7.Management's Discussion and Analysis o...
1587,1762278,NO_TICKER,10-K,2020-05-21 00:00:00.0,2020-02-29 00:00:00.0,>Item 1A.Risk Factors.Item 2.Properties.,>Item 7.Management's Discussion and Analysis o...
1589,1770345,NO_TICKER,10-K,2020-05-21 00:00:00.0,2020-02-29 00:00:00.0,>Item 1A.Risk Factors.Item 2.Properties.,>Item 7.Management's Discussion and Analysis o...
1591,1779026,NO_TICKER,10-K,2020-05-21 00:00:00.0,2020-02-29 00:00:00.0,>Item 1A.Risk Factors.Item 2.Properties.,>Item 7.Management's Discussion and Analysis o...
1593,1788503,NO_TICKER,10-K,2020-05-21 00:00:00.0,2020-02-29 00:00:00.0,>Item 1A.Risk Factors.Item 2.Properties.,>Item 7.Management's Discussion and Analysis o...
1595,1796587,NO_TICKER,10-K,2020-05-21 00:00:00.0,2020-02-29 00:00:00.0,>Item 1A.Risk Factors.Item 2.Properties.,>Item 7.Management's Discussion and Analysis o...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
108,71180,NVE,10-K,2020-02-24 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk FactorsEach Registrant is subje...,>Item 7.Management's Discussion and Analysis o...
1360,90144,NVE,10-K,2020-02-24 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk FactorsEach Registrant is subje...,>Item 7.Management's Discussion and Analysis o...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
394,1733998,NWN,10-K,2020-03-02 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORSNW Holdings and NW Natu...,>ITEM 7. MANAGEMENT'S DISCUSSION AND ANALYSIS ...
1332,1733998,NWN,10-K,2020-03-02 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORSNW Holdings and NW Natu...,>ITEM 7. MANAGEMENT'S DISCUSSION AND ANALYSIS ...
1436,73020,NWN,10-K,2020-03-02 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORSNW Holdings and NW Natu...,>ITEM 7. MANAGEMENT'S DISCUSSION AND ANALYSIS ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
145,1474464,NYRT,10-K,2020-03-16 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors. Set forth below are th...,>Item 7. Management s Discussion and Analysis ...
1094,1595527,NYRT,10-K,2020-03-19 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors.Set forth below are the...,>Item 7. Management s Discussion and Analysis ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
755,17797,PGN,10-K,2020-02-20 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORS In addition to other di...,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...
1146,1094093,PGN,10-K,2020-02-20 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORS In addition to other di...,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...
1253,37637,PGN,10-K,2020-02-20 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORS In addition to other di...,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
399,79732,POM,10-K,2020-02-11 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORS for additional informat...,>ITEM 7. MANAGEMENT'S DISCUSSION AND ANALYSIS ...
621,1135971,POM,10-K,2020-02-11 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORS for additional informat...,>ITEM 7. MANAGEMENT'S DISCUSSION AND ANALYSIS ...
846,27879,POM,10-K,2020-02-11 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORS for additional informat...,>ITEM 7. MANAGEMENT'S DISCUSSION AND ANALYSIS ...
1102,8192,POM,10-K,2020-02-11 00:00:00.0,2019-12-31 00:00:00.0,>ITEM 1A. RISK FACTORS for additional informat...,>ITEM 7. MANAGEMENT'S DISCUSSION AND ANALYSIS ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
184,95574,SCG,10-K,2020-02-20 00:00:00.0,2019-12-31 00:00:00.0,">Item 1A. Risk Factors Our business, operation...",>Item 7. Management s Discussion and Analysis ...
538,91882,SCG,10-K,2020-02-28 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors DESC s business is infl...,>Item 7. Management s Discussion and Analysis ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
1008,1756640,WGL,10-K,2020-05-12 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors You should carefully co...,>Item 7. Management s Discussion and Analysis ...
1301,104819,WGL,10-K,2020-03-02 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk Factors (continued)WGL and Alta...,>ITEM 7. MANAGEMENT S DISCUSSION AND ANALYSIS ...

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
570,1282266,WIN,10-K,2020-05-19 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk FactorsRisks Related to Chapter...,>Item 7.Management s Discussion and Analysis o...
1440,1585644,WIN,10-K,2020-05-19 00:00:00.0,2019-12-31 00:00:00.0,>Item 1A. Risk FactorsRisks Related to Chapter...,>Item 7.Management s Discussion and Analysis o...

' Seems like we have lots of differing CIKs for the same ticker. Also some rows with no ticker'

In [ ]:
"""
Documentation reads:
- You can merge with the text data for the two sections (MD&A discussion and Risk) using fiscal year and CIK code.
- The provided "permanent ID" can be used to get historical data for the same stock and get around CIK and ticker changes.

Maybe it would be smart to replace CIK/TICKER with the permanent ID given in the predictions file. Also makes sense
to group the predictions with the row it pertains to (ie 2012 report is matched with the target variables 12M change
in 2012)
"""

# Predictions

In [2]:
relevant_cols = ["PERMID", "CIK", "Ticker", "year", "FilingDate", "company_name", "Dividend Payer", "DPS growth", "DPS cut", "zEnvironmental", "dEnvironmental", "sector"]
predictions = pd.read_excel("predictions.xlsx", sheet_name="data", skiprows=32, usecols=relevant_cols)
predictions.columns = ["perm_id", "cik", "ticker", "year", "filing_date", "company_name", "is_dividend_payer", "dps_change", "is_dps_cut", "z_environmental", "d_environmental", "sector"]

In [3]:
predictions.head()

,perm_id,cik,ticker,year,filing_date,company_name,is_dividend_payer,dps_change,is_dps_cut,z_environmental,d_environmental,sector
0,PERMID_229,1090872,A,2012,2012-12-20,AGILENT TECHNOLOGIES INC,1.0,0.421053,0.0,2.449925,-1.408006,Health Care
1,PERMID_229,1090872,A,2013,2013-12-19,AGILENT TECHNOLOGIES INC,1.0,0.137652,0.0,1.666993,1.117957,Health Care
2,PERMID_229,1090872,A,2014,2014-12-22,AGILENT TECHNOLOGIES INC,1.0,-0.275862,1.0,2.154238,-0.193752,Health Care
3,PERMID_229,1090872,A,2015,2015-12-21,AGILENT TECHNOLOGIES INC,1.0,0.139535,0.0,2.069083,0.039619,Health Care
4,PERMID_229,1090872,A,2016,2016-12-20,AGILENT TECHNOLOGIES INC,1.0,0.137652,0.0,2.087030,-0.112717,Health Care

In [18]:
predictions['perm_id'] = predictions['perm_id'].str.replace(r"[^0-9]",'')

In [37]:
predictions.head(15)

,perm_id,cik,ticker,year,filing_date,company_name,is_dividend_payer,dps_change,is_dps_cut,z_environmental,d_environmental,sector
0,229,1090872,A,2012,2012-12-20,AGILENT TECHNOLOGIES INC,1.0,0.421053,0.0,2.449925,-1.408006,Health Care
1,229,1090872,A,2013,2013-12-19,AGILENT TECHNOLOGIES INC,1.0,0.137652,0.0,1.666993,1.117957,Health Care
2,229,1090872,A,2014,2014-12-22,AGILENT TECHNOLOGIES INC,1.0,-0.275862,1.0,2.154238,-0.193752,Health Care
3,229,1090872,A,2015,2015-12-21,AGILENT TECHNOLOGIES INC,1.0,0.139535,0.0,2.069083,0.039619,Health Care
4,229,1090872,A,2016,2016-12-20,AGILENT TECHNOLOGIES INC,1.0,0.137652,0.0,2.087030,-0.112717,Health Care
5,229,1090872,A,2017,2017-12-21,AGILENT TECHNOLOGIES INC,1.0,0.120996,0.0,2.001802,-0.005981,Health Care
6,229,1090872,A,2018,2018-12-20,AGILENT TECHNOLOGIES INC,1.0,0.095847,0.0,1.965649,-0.025396,Health Care
7,229,1090872,A,2019,2019-12-19,AGILENT TECHNOLOGIES INC,1.0,NaN,NaN,1.822010,-0.051232,Health Care
8,2606,1675149,AA,2016,2017-03-15,ALCOA CORP,1.0,-2.000000,1.0,-0.765456,1.110362,Commodities
9,2606,1675149,AA,2017,2018-02-26,ALCOA CORP,0.0,NaN,NaN,-0.183476,-0.382313,Commodities
10,2606,1675149,AA,2018,2019-02-26,ALCOA CORP,0.0,NaN,NaN,-0.350552,0.068687,Commodities
11,2606,1675149,AA,2019,2020-02-21,ALCOA CORP,0.0,NaN,NaN,-0.191054,-0.427564,Commodities
12,1061,1264707,AACC,2010,2011-03-04,ASSET ACCEPTANCE CAPITL CP,0.0,NaN,NaN,NaN,NaN,Financials
13,1061,1264707,AACC,2012,2013-03-07,ASSET ACCEPTANCE CAPITL CP,NaN,NaN,NaN,NaN,NaN,Financials
14,2352,948846,AAI,2010,2011-02-04,AIRTRAN HOLDINGS INC,0.0,NaN,NaN,NaN,NaN,Industrials

In [36]:
values = predictions["perm_id"].to_list()
keys_cik = predictions["cik"].to_list()
keys_ticker = predictions["ticker"].to_list()
ticker_cik_to_permid = dict(zip(keys_cik + keys_ticker, values + values))

In [41]:
"""
If company A [2010-2020] and B[2010-2015] where B merged into A in 2015, do we discard everything for B? YES

-> Moving from 2020 to 2010, a ticker/cik must have been seen in the future (backwards in this case) or exists
in the permanent ticker/cik dict
"""
these_rows = data_by_year["2018"][data_by_year["2018"].ticker == "A"]

In [54]:
these_rows.drop_duplicates()

,cik,ticker,form_type,filing_date,fiscal_period_end,item1a_risk,item7_mda
1266,1090872,A,10-K,2018-12-20 00:00:00.0,2018-10-31 00:00:00.0,>Item 1A. Risk Factors Our operating results a...,>Item 7. Management's Discussion and Analysis ...